FROM node:20-alpine

WORKDIR /app

# Copy package files first for caching
COPY package*.json ./

# Install dependencies inside the container
RUN npm install

# Copy the rest of the files
COPY . .

# Expose the Vite port
EXPOSE 8080

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0"]